version: '2'
services:
  web:
    build:
      context: ./
      dockerfile: web.docker
    networks:
      - laravel-net
    volumes:
      - ./www:/var/www
    ports:
      - "80:80"
    depends_on:
      - app
  app:
    build:
      context: ./
      dockerfile: app.docker
    networks:
      - laravel-net
    volumes:
      - ./www:/var/www
    depends_on:
      - mysql
      - redis
  mysql:
    restart: always
    image: mysql:latest
    networks:
      - laravel-net
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD"
      - "MYSQL_DATABASE"
      - "MYSQL_USER"
      - "MYSQL_PASSWORD"
    ports:
      - "3306:3306"
  redis:
    restart: always
    image: redis:latest
    command: redis-server --appendonly yes
    networks:
      - laravel-net
    volumes:
      - ./redis:/data
    ports:
      - "6379:6379"

networks:
  laravel-net:
    driver: bridge
